/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

/**
 *
 * @author Frank
 */
public class CuadernoPrecio extends javax.swing.JFrame {

    private RegistroRopa padre;
    /**
     * Creates new form CuadernoPrecio
     */
    public CuadernoPrecio(RegistroRopa padre) {
        initComponents();
        this.padre=padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPantalon = new javax.swing.JButton();
        btnCamiseta = new javax.swing.JButton();
        btnVestido = new javax.swing.JButton();
        btnBlusa = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Group 82.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnPantalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Group 83.png"))); // NOI18N
        btnPantalon.setBorder(null);
        btnPantalon.setContentAreaFilled(false);
        btnPantalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalonActionPerformed(evt);
            }
        });
        jPanel1.add(btnPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        btnCamiseta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Group 84.png"))); // NOI18N
        btnCamiseta.setBorder(null);
        btnCamiseta.setContentAreaFilled(false);
        btnCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamisetaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCamiseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btnVestido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Group 85.png"))); // NOI18N
        btnVestido.setBorder(null);
        btnVestido.setContentAreaFilled(false);
        btnVestido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVestidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVestido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        btnBlusa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Group 86.png"))); // NOI18N
        btnBlusa.setBorder(null);
        btnBlusa.setContentAreaFilled(false);
        btnBlusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlusaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBlusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Group 87.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBlusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlusaActionPerformed

        Blusas blu = new Blusas(this);
        blu.setLocationRelativeTo(this);
        blu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBlusaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        salir();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPantalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalonActionPerformed

        Pantalones pant = new Pantalones(this);
        pant.setLocationRelativeTo(this);
        pant.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPantalonActionPerformed

    private void btnCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamisetaActionPerformed

        Camisetas cami = new Camisetas(this);
        cami.setLocationRelativeTo(this);
        cami.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCamisetaActionPerformed

    private void btnVestidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVestidoActionPerformed

        Vestidos vesti = new Vestidos(this);
        vesti.setLocationRelativeTo(this);
        vesti.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVestidoActionPerformed

    private void salir(){
        padre.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuadernoPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuadernoPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuadernoPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuadernoPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuadernoPrecio(new RegistroRopa()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlusa;
    private javax.swing.JButton btnCamiseta;
    private javax.swing.JButton btnPantalon;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVestido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
